name: flutter_maplibre_gl
repository: https://github.com/maplibre/flutter-maplibre-gl

packages:
  - packages/*

ignore:
  # e.g. ignore example apps
  - 'packages/**/example'

scripts:
  analyze:
    exec: dart analyze .

